### ISSUE TITLE
Cannot download the data.zip in scripts

### ISSUE THREAD

**Issue by YaldaAmidi227** [luo-group/ConFit#2]
Hi, thank you for sharing your code. I tried to download your data to test the model but I get this error: 

```
Archive:  data.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of data.zip or
        data.zip.zip, and cannot find data.zip.ZIP, period.
```
Could you help me how can I solve this issue?
Thanks

**Comment by JunmingZhao20** [comment]
Hi, thank you for bringing this to our attention!

We’ve updated our repository with a new script that should help resolve the problem. Please try using the new `scripts/download.sh` script to download the dataset.

If you continue to experience issues, please let us know, and we’ll be happy to assist further.

Best regards

**Comment by YaldaAmidi227** [comment]
Thank you I can download it.
